application: folkloric-air-861
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /templates
  static_dir: templates

- url: /.*
  script: helloworld.app
